### ISSUE TITLE
3.0 SIF images are not writtable

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity-userdocs#12]
3.0 SIF images are not writable
this needs to be detailed on the docs, to aware users.

- examples like how to run MPI with singularity use a `copy` cmd that is deprecated in 3.0 due the non writable image.

**Comment by devprincess** [comment]
Sorry about closing it before, going to leave this one open until I get a PR on this new section :+1: thank you! @ArangoGutierrez

**Comment by devprincess** [comment]
Do you have any ideas how can I obtain these examples @ArangoGutierrez , I'm also assuming this is something to be added to `3.0` am I correct? thank you

**Comment by GodloveD** [comment]
Just going through some older issues here.  @ArangoGutierrez do you know if this is still a problem with the current version of the docs?  Can you suggest which page this info should be added to please?

**Comment by dtrudg** [comment]
The build page calls this out:

```
build can produce containers in two different formats that can be specified as follows.

    compressed read-only Singularity Image File (SIF) format suitable for production (default)
...
```
