### ISSUE TITLE
wrong version on install instructions

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity-userdocs#13]
the link [https://www.sylabs.io/guides/2.5/user-guide/quick_start.html#installation](https://www.sylabs.io/guides/2.5/user-guide/quick_start.html#installation) which states that will take you to a `2.5` install, have instructions for `2.6`

**Comment by jchavezlavalle** [comment]
Thank you, this has already been updated for 2.5 version @ArangoGutierrez

**Comment by GodloveD** [comment]
There is still a problem here @devprincess.  

Compare the version in the address bar with the version in the instructions. 

<img width="997" alt="screen shot 2018-09-06 at 3 51 34 pm" src="https://user-images.githubusercontent.com/7672924/45181578-d47a8e80-b1ec-11e8-8d0e-c2b5efc36bc7.png">

**Comment by jchavezlavalle** [comment]
@ArangoGutierrez @GodloveD This change is included on the tarball I sent to @jmstover last friday, also including updates from the last technical writer (updates that Greg sent to me), looking forward to see those changes live :) thanks!

**Comment by jchavezlavalle** [comment]
@ArangoGutierrez this has been solved, please check here https://www.sylabs.io/guides/2.5/user-guide/quick_start.html#installation and thank you :+1:
