### ISSUE TITLE
missing step in 2.5 install guide

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity-userdocs#135]
Please fix the following issue:

https://github.com/sylabs/singularity/issues/1763

It is a bit of an old issue, but since we have the docs out there still I think it would be good to update it!

**Comment by dtrudg** [comment]
The `2.5` instructions should refer to `2.5.2` (as the latest/last release in that series), but the `./autogen.sh` is not required as we are instructing the user to download prepared release tarballs where `configure` is already present (i.e. `./autogen.sh` was run before the tarball was created)

**Comment by dtrudg** [comment]
Closed by #251
