### ISSUE TITLE
User Instalation  guide wrong branch in instructions

### ISSUE THREAD

**Issue by Sabryr** [apptainer/singularity-userdocs#14]
I see the following instruction will be confusing for a user who has less knowledge of git

in https://www.sylabs.io/guides/2.6/user-guide/quick_start.html
git clone https://github.com/singularityware/singularity.git
cd singularity
git fetch --all
git checkout 2.6.0

This will result in a HEAD less state as there is not branch called 2.6.0

 git branch -a
  master
  release-2.6  
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/origin/release-2.6
  remotes/origin/vault/1.x
  remotes/origin/vault/2.x
  remotes/origin/vault/development
  remotes/origin/vault/master-2.x
  remotes/origin/vault/release-2.0.x
  remotes/origin/vault/release-2.1.x
  remotes/origin/vault/release-2.2.x
  remotes/origin/vault/release-2.3.x
  remotes/origin/vault/release-2.4
  remotes/origin/vault/release-2.5

**Comment by jmstover** [comment]
@Sabryr 
  Currently `release-2.6` matches tag `2.6.0` (git rev-parse HEAD) but that is _not_ a guarantee to always be the case. We could merge in PR's to release-2.6 so they'll already exist in the branch for _future_ releases in the 2.6.x series. 

  The tag is the location of record. It's the location release tarballs are created from. The branch is there for development purposes, not release.

  We also have included building from a release tarball
  https://www.sylabs.io/guides/2.6/user-guide/installation.html#install-a-specific-release
