### ISSUE TITLE
highlight preferred bootstrap agents

### ISSUE THREAD

**Issue by rherban** [apptainer/singularity-userdocs#154]
## Which Document page:

https://www.sylabs.io/guides/3.1/user-guide/definition_files.html

### Expected results:

The library/docker/shub agents should be listed as preferred agents or highlighted in some way.  The older agents should remain listed for completeness.

related to #93

**Comment by GodloveD** [comment]
Agreed.  Also `scratch` bootstrap agent should be highlighted as the most flexible option for building a container from scratch.
