### ISSUE TITLE
SCIF apps fixes

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity-userdocs#155]
Heyo! On [this page](https://www.sylabs.io/guides/3.1/user-guide/cli/singularity_apps.html?highlight=scif)

![image](https://user-images.githubusercontent.com/814322/56459825-56c45700-6367-11e9-8e25-9f55d50c438c.png)

There are a few issues, noted here:

 - SCIF stands for the "Scientific Filesystem" - they are not "Singularity apps"
 - The link should be https://sci-f.github.io (not containers.ftw)

And then on [this page](https://www.sylabs.io/guides/3.1/user-guide/running_services.html?highlight=Standard#making-it-fancy) the reference to SCIF should not be Standard Container Integration Format, but Scientific Filesystem. Thanks muchly!

**Comment by vsoch** [comment]
hey @devprincess where can I look to see the updated page?

**Comment by GodloveD** [comment]
Heya @vsoch it seems that the `--apps` command has been moved into the `inspect` command in current master.  These docs are automatically generated from the Singularity command line.  So I think the upshot is that we will probably not fix until 3.3 comes out (probably <2 weeks) and that the fix will involve removing this command from the docs altogether and adding the link in question to the `inspect` command.  Sorry that we got the wrong links on the first try.

**Comment by vsoch** [comment]
No worries @GodloveD, thanks for letting me know! I'll add a note to take a look in a couple of weeks.

**Comment by jchavezlavalle** [comment]
@vsoch https://www.sylabs.io/guides/3.1/user-guide/running_services.html?highlight=Standard#making-it-fancy should be updated and also the same section for version 3.2. Since the documentation from the inspect command is on the other repo, it is open on here ready to be reviewed -> https://github.com/sylabs/singularity/pull/3613. I'll add you on the review. Thanks !

**Comment by vsoch** [comment]
Looks great, thanks @devprincess. I'll take a look at the other PR now.
