### ISSUE TITLE
Pull destination

### ISSUE THREAD

**Issue by HelenCousins** [apptainer/singularity-userdocs#158]
## Which Document page:

On what page is the problem?

https://www.sylabs.io/guides/3.1/user-guide/build_env.html#pull-folder

### Expected results:

An answer to the question 'how do I set the pull destination?'

### Actual results:

There is no answer, and no link to an answer; if I go to https://www.sylabs.io/guides/3.1/user-guide/cli/singularity_pull.html it also does not tell me how to pull to other than CWD.

In previous versions setting SINGULARITY_CACHEDIR worked; it does not appear to work in 3.1.1

**Comment by rherban** [comment]
Thanks for pointing this out.  You can specify the destination with a full path for the output file, like so:
singularity pull /tmp/centos.sif library://centos

We'll get the docs updated (and we're always welcoming of a pull request with suggestions).

**Comment by jchavezlavalle** [comment]
Hi @HelenCousins,
 
Setting up the `SINGULARITY_CACHEDIR` environment variable will work as follows, you will need to do the following: (this example assumes you own a `/tmp/cache-tmp` folder, but you can specify the folder you want to cache your images on)

1. First set and export the `SINGULARITY_CACHEDIR` environment variable like so:

```sh
$ export SINGULARITY_CACHEDIR=/tmp/cache-tmp
```
 2. After this you can just simply pull using sudo privilege and the `-E` flag:

```sh
$ sudo -E singularity pull library://alpine
```

You can then go and verify that the image has been correctly cached in the `/tmp/cache-tmp` folder.

output:
```
$ sudo -E singularity pull library://alpine
INFO:    Key with ID EDECE4F3F38D871E not found in local keyring, downloading from keystore...
INFO:    Container is signed
Data integrity checked, authentic and signed by:
	Sylabs Admin <support@sylabs.io>, Fingerprint 8883491F4268F173C6E5DC49EDECE4F3F38D871E
WARNING: no local key matching entity
$ cd /tmp/cache-tmp/
$ ls
library
$ cd library/
$ ls
sha256.63259fd0a2acb88bb652702c08c1460b071df51149ff85dc88db5034532a14a0
$ cd sha256.63259fd0a2acb88bb652702c08c1460b071df51149ff85dc88db5034532a14a0/
$ ls
alpine_latest.sif
```

**Comment by HelenCousins** [comment]
echo $SINGULARITY_CACHEDIR
/tmp/cache-tmp

singularity pull library://alpine

ls .
alpine_latest.sif

ls /tmp/cache-tmp/library/sha256.63259fd0a2acb88bb652702c08c1460b071df51149ff85dc88db5034532a14a0/
alpine_latest.sif


OK, it cached over in /tmp/cache-tmp, but it put the .sif in CWD which I didn't really want, the problem is with quotaing and simply not having enough space.  But I believe I can work around it.
