### ISSUE TITLE
Heading for user docs on sylabs.io should read 'Documentation for users'

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity-userdocs#166]
Originally reported by @jack-morrison, confirmed by me.

Looks like there are some small typos at `https://sylabs.io/docs`.

`3.0`, `3.1`, and `3.2` all have: `Documentation for user`, which I believe should be `Documentation for users`.

**Comment by jack-morrison** [comment]
@jscook2345 This was fixed during the website redesign, and can be closed. Docs page now simply indicates 'Admin Guide' or 'User Guide'.

**Comment by jscook2345** [comment]
@jack-morrison Thanks for the heads up! Closing!
