### ISSUE TITLE
Create a document describing good practices for creating singularity containers

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity-userdocs#193]
I think having some general guidelines for users would be a good idea.

**Comment by jscook2345** [comment]
See also: https://singularity.lbl.gov/docs-docker#best-practices

**Comment by jscook2345** [comment]
Here is something we have in the userdocs:

https://www.sylabs.io/guides/3.2/user-guide/definition_files.html?highlight=best%20practice#best-practices-for-build-recipes

**Comment by dtrudg** [comment]
I think what we have there is fine for now, unless there are any specific additions needed which should could be noted on this issue if it's reopened.

We are covering everything in the old LBL guide with the exception of the 'always run ldconfig' which always seemed strange to me. It won't really fix the issues observed where people copy in libraries into the container but do not have the dir in their `/etc/ld.so.conf(.d)`
