### ISSUE TITLE
Docs: create latest 

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity-userdocs#196]
Heyo!

I think it might be useful to provide a link to whatever version of Singularity is the latest. For example, I commonly will link to a page, such as:

https://sylabs.io/guides/3.2/user-guide/running_services.html

And I'd really like to be able to link to "the latest version of that page," something like:

https://sylabs.io/guides/latest/user-guide/running_services.html

It would mean releasing a "latest" group as a clone of (whatever version string is the latest). It shouldn't be too hard because, at least on readthedocs, this is done by default. Eg.., see https://psutil.readthedocs.io/en/latest/ for an example.

**Comment by sushma-4** [comment]
@jmstover Is it something that needs to be updated in the .RST files we write? Or do you do this when you update them?

**Comment by jmstover** [comment]
@sushma-4 
This is outside of my control now. @wobito may have an idea if it can be implemented with the new hosting. It did exist on the previous host.

**Comment by wobito** [comment]
No Problem! I'll set this up so /latest/ redirects to the set latest version of the docs!

**Comment by vsoch** [comment]
Awesome! Yeah I was thinking that it can be a build step that just links a static hosted folder to another, or an actual meta tag with a redirect (probably the better of the two :P)

**Comment by wobito** [comment]
@vsoch just about to deploy that exact solution. :D

**Comment by wobito** [comment]
not 100%, but these work
https://sylabs.io/guides/latest/user-guide 
https://sylabs.io/guides/latest/admin-guide

This does not.. will continue to find a solution
https://sylabs.io/guides/latest/user-guide/running_services.html

**Comment by vsoch** [comment]
Maybe a mod rewrite rule?

https://stackoverflow.com/questions/8416042/htaccess-redirect-all-pages-under-a-folder-to-new-domain

The top two work great!

**Comment by sushma-4** [comment]
@wobito Thank you! Maybe the CRI documentation here https://sylabs.io/guides/cri/1.0/user-guide/ should work with `latest` as well. Though we are not releasing a new version immediately, but when we do, it should be able to direct to the latest one.

**Comment by DrDaveD** [comment]
We have the "main" link at https://apptainer.org/docs.
