### ISSUE TITLE
CI/CD magic!!

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity-userdocs#199]
### Which Document page:

All of 'em!

### Expected results:

CI/CD magic!

### Actual results:

No CI/CD magic!  

### Explanation:  

I think it should be possible to hook this repo into Circle and have it perform the following CI checks/actions with each PR.  
- Run `make html` and build the pages successfully 
- Make sure that there are no warnings when pages are built (all refs have links point to them etc.)
- Run [linklint](http://www.linklint.org/) on the pages (or equivalent tool if anyone has a preference) and ensure that all internal and external links go _somewhere_.  

Additionall, I think that we should perform CD by automating the following action after a merge into master.
- Run `make html` and push the resulting files to the appropriate GitHub repo so they will be live.  

It would be magical...

![tenor](https://user-images.githubusercontent.com/7672924/60200353-2f748500-9803-11e9-8510-509e2379b69c.gif)

**Comment by GodloveD** [comment]
See also https://github.com/sylabs/singularity-cri-userdocs/issues/14

**Comment by jmstover** [comment]
You're ignoring `make latexpdf` and `make epub` though ...

**Comment by GodloveD** [comment]
Right.  But the same basic ideas apply to those too.

**Comment by brianclemens** [comment]
Fixed in  d80f0780959bc428e5dedb0896af34f0f936575e
