### ISSUE TITLE
 Link to Basic Usage unavailable

### ISSUE THREAD

**Issue by sashayakovtseva** [apptainer/singularity-userdocs#209]
Transferring sylabs/singularity-cri-userdocs#20 here.

**Comment by sushma-4** [comment]
Can you please mention where in the userdocs should it be pointing to?

**Comment by sashayakovtseva** [comment]
I think https://sylabs.io/guides/cri/1.0/user-guide/examples.html would fit there.

**Comment by dtrudg** [comment]
This seems to be working at: https://sylabs.io/guides/3.4/user-guide/oci_runtime.html
