### ISSUE TITLE
document need for cryptsetup-bin

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity-userdocs#211]
Looks like `cryptsetup-bin` has been added as a new dependency (presumably to support encrypted containers).  This will need to be documented in the 3.4 version of the docs.

**Comment by WestleyK** [comment]
Please use `cryptsetup`, (instead of `cryptsetup-bin`).

`cryptsetup-bin` looks to be a dependency for `cryptsetup`, and they both need to be installed to function properly.

**Comment by kmanalo** [comment]
I noticed this as well, should this message be altered for the configure then?

```
 checking: cryptsetup... no
unable to find the cryptsetup program, is the package cryptsetup-bin installed?
```

**Comment by dtrudg** [comment]
> Please use `cryptsetup`, (instead of `cryptsetup-bin`).
> 
> `cryptsetup-bin` looks to be a dependency for `cryptsetup`, and they both need to be installed to function properly.

@WestleyK - I'm not sure this is the case. `cryptsetup` on debian based distros includes recommends on initramfs related packages that we don't need. The `cryptsetup-bin` command line package should be sufficient, and avoid bringing in some things that are only needed for LUKS encryption on the host.

Can you elaborate on what error you see (if any) with `cryptsetup-bin` and without `cryptsetup`?

**Comment by dtrudg** [comment]
Closing this. I'm pretty confident `cryptsetup-bin` is sufficient here. Please reopen with detail if issues found anywhere.
