### ISSUE TITLE
suggestion: intuitive url for docs base

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity-userdocs#212]
Just a suggestion - sometimes I want to jump from a previous link to the base docs page (e.g., if I'm looking at user docs and wants to select a different version, or go to admin docs) so it's logical to take this url:

```
https://www.sylabs.io/guides/3.1/user-guide/
```
and jump to this one:
```
https://sylabs.io/guides/
```
But this is obviously 404 because the correct one (that never seems to be in my browser history) ends with docs. Would it be a reasonable thing to have the intuitive url, `https://sylabs.io/guides/` at least redirect to the docs page?  And any updates on "latest" e.g., https://sylabs.io/guides/latest/user-guide/quick_start.html#executing-commands. Thanks!

**Comment by DrDaveD** [comment]
We have https://apptainer.org/docs now.
