### ISSUE TITLE
Links to latest

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity-userdocs#228]
Heyo! The "latest" links don't refer to the actual latest (3.3). E.g.,:

https://sylabs.io/guides/latest/user-guide
https://sylabs.io/guides/latest/admin-guide/

Maybe there should be a release checklist to update this?

**Comment by sushma-4** [comment]
@wobito perhaps you had a fix for this?

**Comment by wobito** [comment]
Yup about to merge the fix shortly

**Comment by wobito** [comment]
Updated in most recent update to website.
