### ISSUE TITLE
Broken Links docs

### ISSUE THREAD

**Issue by arshadkazmi42** [apptainer/singularity-userdocs#23]
In userdocs, on these pages
https://www.sylabs.io/guides/3.0/user-guide/build_a_container.html
https://www.sylabs.io/guides/3.0/user-guide/security_options.html

Edit on github link is broken, on investigating further, I found that this file `build_a_container.rst` is missing in master branch. But its present in branches `3.0`, `2.6`, `2.5`.

So, is it intentionally removed from master branch or it has been removed by mistake.
If its intentionally removed from master branch, then the docs edit option should redirect to any of the other branches which has that file.

Its same issue with `security_options.rst` also

If someone can confirm this, I can work on fixing it.

**Comment by jchavezlavalle** [comment]
Hey @arshadkazmi42 :) we are currently updating master branch to the latest `3.0`, yesterday added new sections to the `3.0` docs, so this will be updated now by us, thanks for letting us know!

**Comment by arshadkazmi42** [comment]
Ok. Cool :+1:
