### ISSUE TITLE
clarification on kernel version required and recommended

### ISSUE THREAD

**Issue by rvalieris** [apptainer/singularity-userdocs#235]
I believe the installation page should describe what kernel version is required to run singularity properly and maybe also describe which features will / will not work with specific kernel versions.

Right now only the fakeroot page mentions kernel versions:
`This feature requires a Linux kernel >= 3.8, but the recommended version is >= 3.18`
but it doesn't say why 3.18 is recommended, or what will not work on 3.8.

there are also a few other pages what mention "recent kernel" without actually specifying what a recent kernel is in terms of version.

**Comment by dtrudg** [comment]
Hi @rvalieris - thanks for noting this. I agree that more precision would be useful here. One of the extra things we need to think about around this is that the many users in HPC land are on CentOS / RHEL where many features are being back ported into older kernels. We don't want to put them off trying things which will work - but that requires working out specific revision numbers of kernel packages, or RHEL point releases that provide what's needed.

**Comment by robertlugg** [comment]
The other problem is that I believe the --fakeroot option requires that the user be added to a linux group.

**Comment by dtrudg** [comment]
`--fakeroot` requires that the user must be setup in the `/etc/subuid` and `/etc/subgid` files. We need more on that, for sure.

**Comment by akesandgren** [comment]
You need a good example for the subuid file for sure. (at least there is none in the 3.4 manual)

**Comment by dtrudg** [comment]
This is now addressed in the https://github.com/sylabs/singularity-admindocs/ text - where the detailed installation information is kept. Notes on kernel versions and fakeroot are in the admin guide.

The detailed information in the admin guide is now reference from the quick start section of the userdocs.
