### ISSUE TITLE
Explain writable vs writable-tmpfs vs overlay

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity-userdocs#248]
There is confusion over what `--writable` does vs `--writable-tmpfs` and `--overlay`.  This is understandable given the CLI help strings, and that they are not really addressed in the docs in a comparative manner.

Try to clarify this.

See e.g. https://github.com/sylabs/singularity/issues/3243 https://github.com/sylabs/singularity/issues/4546

**Comment by extinctpotato** [comment]
Hello. 

I would like to describe this feature, as I've had success manipulating the SIF image to include the overlay using siftool and then using this overlay using the `--writable` flag.

If you give me the green light, I'll be happy to provide.

**Comment by dtrudg** [comment]
Hi @extinctpotato - we are always very keen to say 'yes' to user contributions. That would be great. Thanks!

**Comment by tomaszgielda** [comment]
Hi, for some background, @extinctpotato is on our team at Antmicro and we're using this feature in some of our use cases where it's very helpful but we didn't find it until recently, so we'll be sending a PR with this docs update this week
