### ISSUE TITLE
Consider moving installation instructions to admindocs only?

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity-userdocs#289]
The installation instructions in the userdocs repo here, and the admindocs repo (which is undergoing renovation for 3.5) are going to be duplicating content.

I'm thinking it might be better to move the majority of installation content to the admin docs, and just leave a reference and maybe the minimal install from source instructions here?

Any thoughts @ikaneshiro ?

**Comment by ikaneshiro** [comment]
@dctrud Makes sense. As long as users installing Singularity an a personal desktop/laptop can quickly get up and running. Leaving instructions to install from source in the user docs and then linking to the admin docs for installing from `rpm`/`tar` should work well because I assume sysadmins are mostly installing Singularity in that manner.

**Comment by jmstover** [comment]
I'll speak up here... I would just do either EPEL or Debian install on the User side. Then have the full Source/Package build in the Admin. Sure, link to it from the User guide, but... 

*Generally* ... the Users just want to get up and running as quick as possible. That would be installing `singularity-container` (Deb), or from EPEL... even if not the most recent version.

**Comment by ikaneshiro** [comment]
@jmstover An issue I see with that is that we version our docs in sync with singularity. I feel like it would be confusing to users to give instructions in the 3.5 docs that will cause users to install an older version like 3.2.

**Comment by dtrudg** [comment]
Not sure about this - I'm firmly against including deb `singularity-container` instructions at all at the moment. I think they need to be removed. The docs are for a specific 3.x version that is not available, `singularity-container` will give you a 2.x and that's surprising.

My thought was that you *can* build Singularity from source as a non-root user, albeit userns only (this needs calling out in docs better) but to install from a package you have to be an admin on whatever machine you are using.

I guess it depends a bit on the audience. If we assume a lot of Singularity users are using it on shared systems, they are relatively likely not to have a Linux machine of their own. :man_shrugging:

**Comment by dtrudg** [comment]
![Screenshot at 2020-01-07 08-47-15](https://user-images.githubusercontent.com/4522799/71903717-9c76b900-315c-11ea-9bd9-dd78670ea0b4.png)

**Comment by jmstover** [comment]
Yeah, I understand that... But _most_ users don't want to compile stuff. They just want to install it. 

```
NOTE: This could give you an older version as it's community maintained ... 
sudo yum install epel-release
sudo yum install singularity

For a recent version release, see Building from Source in the Admin Guide
```

or something.

Do as you see fit though... Doing a non-suid install is always an option assuming the system supports User Namespace.
