### ISSUE TITLE
Missing documentation for the syntax of definition files

### ISSUE THREAD

**Issue by chenzhekl** [apptainer/singularity-userdocs#30]
There should probably be a section describing the syntax of definition files like what Docker did for Dockerfile.

**Comment by jchavezlavalle** [comment]
@chenzhekl It's in here -> https://www.sylabs.io/guides/2.6/user-guide/container_recipes.html

**Comment by chenzhekl** [comment]
@devprincess Thank you for the link. Hope that section can be added to the 3.0 doc as well.

**Comment by jchavezlavalle** [comment]
@chenzhekl oh sure, we're working on that for 3.0, still leaving this issue opened until we have this section ready and I'll let you know about it, thank you!

**Comment by GodloveD** [comment]
@chenzhekl care to comment?  https://github.com/sylabs/singularity-userdocs/pull/35

**Comment by chenzhekl** [comment]
@GodloveD Thanks for the work! It looks good to me.

**Comment by jchavezlavalle** [comment]
@GodloveD Think this can be closed now since we have the definition files section on here -> https://www.sylabs.io/guides/3.0/user-guide/definition_files.html @chenzhekl could you confirm? thanks

**Comment by chenzhekl** [comment]
Thanks to you guys! Will close then.
