### ISSUE TITLE
Request for Introduction

### ISSUE THREAD

**Issue by prehensilecode** [apptainer/singularity-userdocs#31]
The 2.5 documentation had a good high level Introduction to Singularity at https://www.sylabs.io/guides/2.5/user-guide/introduction.html

The 3.0 documentation seems to lack this. The brochure version at https://www.sylabs.io/singularity/about/ is not detailed enough.

**Comment by wood-chris** [comment]
I'd agree with this - I wonder if there was a good reason it was removed? I think the security / user model needs explaining to new users (although having said that, the v2.6 docs version was pretty verbose and took me a few reads to vaguely understand it).

In addition,  https://www.sylabs.io/singularity/about/ is now a 404

**Comment by sushma-4** [comment]
A lot has changed since the first time we wrote about Security practices/ models for 2.x series. Recently, this page about [Container Security](https://sylabs.io/guides/3.3/user-guide/security.html) was published that talks about different Security features in Singularity.
