### ISSUE TITLE
Cgroups documentation

### ISSUE THREAD

**Issue by hearnsj** [apptainer/singularity-userdocs#32]
Version of Singularity:
3.0.1-1.fc29

Expected behavior

Documentation. At page https://syslabs.io/guides/3.0/user-guide/cgroups.html the example TOML file is said to be at location /usr/local/etc/singularity/cgroups/cgroups.toml

Actual behavior
On a Fedora 29 system the file is /etc/singularity/cgroups/cgroups.tomp

**Comment by GodloveD** [comment]
I think this depends on how you do the installation.  Did you use the RPM method?  Want to suggest an edit in a PR? @hearnsj

**Comment by GodloveD** [comment]
Heya @hearnsj I just went ahead and took the liberty of suggesting a fix in #181.  Thanks for the suggestion!
