### ISSUE TITLE
Invalid Epub

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity-userdocs#335]
Epub files generated by Sphinx are being rejected by Mac default iBooks app. Open okay in Linux tools for me. 

epubcheck shows invalid stuff which I presume is the issue. Not sure why Sphinx is messing this up.

```
Fatal Error while parsing file: The element type "meta" must be terminated by the matching end-tag "</meta>".
```

**Comment by pedroalvesbatista** [comment]
@brianclemens Any clue on this ?

**Comment by DrDaveD** [comment]
I don't think this is something we care about, closing.
