### ISSUE TITLE
Is the documentation at https://sylabs.io/guides/3.0 outdated ?

### ISSUE THREAD

**Issue by floriankrb** [apptainer/singularity-userdocs#391]
## Which Document page:

https://sylabs.io/guides/3.0/user-guide/installation.html#singularity-on-a-shared-resource

### Expected results:

I should read 

```
    - Security: A discussion of security concerns is discussed at
       https://www.sylabs.io/guides/3.0/admin-guide/admin_quickstart.html

```

This was commited 1 year ago.
 e5ca334 - Remove detailed installation section (to admindocs) (1 year, 3 months ago) 

### Actual results:
The link is actually:

``` 
- Security: A discussion of security concerns is discussed at
    https://www.sylabs.io/guides/2.5.2/user-guide/introduction.html#security-and-privilege-escalation
```

And the link is broken (404)

**Comment by dtrudg** [comment]
Yes - this is expected to be outdated as it historical for the `3.0` version as is seen in the URL. The most up-to-date docs are for the `3.7` version...

https://sylabs.io/guides/3.7/user-guide/

See also the different versions in the menu bar->docs, or at: https://sylabs.io/docs/
