### ISSUE TITLE
Ensure that previous singularity.lbl.gov docs are reproduced

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity-userdocs#408]
I've recently been going through old Google Groups and GitHub issues, and there is a surprising number of references to old tutorials, instructions, or content on the singularity.lbl.gov page. Currently, if the user clicks they are taken to the home of the hpcng user docs, which gives them no idea about the previous content, is confusing, and considered bad practice to have so many broken links. I've discussed this in slack, and there are a few options:

1. Return the CNAME to direct to the old site, which is not desired by gmk. 
2. Have some subset of urls go to the old site, and some to the new one
3. Go through old archives and issues, find all the references URLs, and ensure that they redirect to updated content.

I think the most ideal is #3 but this would take a bit of work - the easiest thing to do would be to actually go through the URLS on the new site and then map them to content on the new site, and then use basic html meta tags to redirect for those pages. In the mean time, an intermediate solution would be to have a middle man page that shows a message "This page is redirecting to a legacy site kept for historical reasons, to navigate to the current singularity site go `<here>`

Here are comments from Greg:

> Going back to the original point, reverting the CNAME back to a website which hasn’t been maintained for years and contains mostly obsolete docs for the current versions of Singularity seems like a really bad idea.

> If you feel this is a major issue, the official site is Gatsby on GitHub. We would love help in adding permalinks to match the old URLs (unless you have a better idea on how to fix). 

> The best case scenario would be for those old URLs to resolve to something relevant and current. I’m open to other ideas.

The framework of the site is irrelevant because redirects are redirects. You can look at the usrse.github.io site for an example of how I did it, and read about the meta tag here. https://www.tutorialspoint.com/How-to-redirect-from-an-HTML-page It's basically just defining the page (based on the URL) and then redirecting somewhere else.

**Comment by DrDaveD** [comment]
I assume you meant "go through the URLS on the *old* site", not *new* site.

What's the URL for the old site?  Is there source for it in a different github repo or somewhere?

Are there particularly important links you think should be directed to the old site, or link subpaths?

**Comment by vsoch** [comment]
You can either parse the Google groups plus both singularity issues / PRs to look for links, or (easier) just get the URLS from the old site (this is the old site https://singularityware.github.io/). The source for that is https://github.com/singularityware/singularityware.github.io/ which is the original docs I made back in 2016.

**Comment by DrDaveD** [comment]
So is it basically /admin-guide and /user-guide that we would need to forward?  We don't have control over the apache configuration so we can't make it forward only when the virtualhost is singularity.lbl.gov, it would have to be for all urls at that path.

**Comment by vsoch** [comment]
I would say all the links under Documentation, except for Archive. I've seen others around (e.g., Getting Help -> Troubleshooting) but hopefully those pages have been reproduced in hpcng.

**Comment by DrDaveD** [comment]
The only thing else under Docs is "links", do you think that's needed too?

In any case, I just realized this request should be under https://github.com/hpcng/singularity-web, not in this repo.  How about you close this and open a new one over there suggesting the specific forwards you would like to see?

**Comment by vsoch** [comment]
I don't think we need to re-create the issue, you could just transfer it?

**Comment by DrDaveD** [comment]
It doesn't look like I have the permissions for that.  I can transfer away, but I don't have the permissions to send it to singularity-web.  Probably somebody does but I think referring to an issue is almost as good.

**Comment by DrDaveD** [comment]
Or I wonder if maybe it would be better to go ahead and leave the CNAME pointing to singularityware.github.io but have the home page there redirect to singularity.hpcng.org.  We could discuss that at the next community meeting.

**Comment by vsoch** [comment]
That’s a great idea! If that works it would preserve the old links but make sure to redirect from the home page. Even if you just add the redirect meta tag to the home page I think that would do it?

**Comment by DrDaveD** [comment]
I'm sorry I completely forgot about this.  It was not discussed at the next community meeting, according to the notes from back then.  I put it on the agenda for the next meeting.

**Comment by DrDaveD** [comment]
Continued in https://github.com/hpcng/singularity-web-lbl/issues/1
