### ISSUE TITLE
 Failed to create user namespace: user namespace disabled

### ISSUE THREAD

**Issue by kevin-furant** [apptainer/singularity-userdocs#435]
`singularity shell lolcow_latest.sif
WARNING: failed to set O_CLOEXEC flags on image
INFO:    Converting SIF file to temporary sandbox...
WARNING: failed to set O_CLOEXEC flags on image
FATAL:   while extracting lolcow_latest.sif: root filesystem extraction failed: extract command failed: WARNING: failed to set O_CLOEXEC flags on image
WARNING: failed to set O_CLOEXEC flags on image
ERROR  : Failed to create user namespace: user namespace disabled
: exit status 1`
How to solve?? thank you!

**Comment by kevin-furant** [comment]
i installed sintularity with conda . conda install -c conda-forge singularity .

**Comment by DrDaveD** [comment]
That's an unprivileged installation so it requires unprivileged user namespaces to be enabled in the Linux kernel.  That's not available on very old kernels, and other kernels (for example those based on RHEL7) require a non-default configuration option to be set.

By the way, this would be a more appropriate question on the main repository https://github.com/apptainer/apptainer or on the mailing list or slack than on this documentation repository.

**Comment by kevin-furant** [comment]
![image](https://user-images.githubusercontent.com/34704037/146702736-a7e3f662-bb23-4685-8556-acbe09528eb6.png)
i have installed it with root.
But it still doesn't work.

**Comment by kevin-furant** [comment]
An Ubuntu subsystem was installed in the Windows 10 system for testing.

**Comment by DrDaveD** [comment]
I guess the Windows System for Linux is not a complete enough emulation for Linux for this.  Somebody else ran into a different issue trying to use conda with singularity recently there, in apptainer/singularity#6340.  

Closing, as there's not likely anything that can be done about this and in any case this the wrong place to discuss it.

**Comment by kevin-furant** [comment]
@DrDaveD  thank you very much! Wls1 for windows linux subsystem needs to be upgraded to WSL2. i have solved it.
