### ISSUE TITLE
Add CLI reference

### ISSUE THREAD

**Issue by multimeric** [apptainer/singularity-userdocs#73]
The old docs had a very useful CLI reference: https://singularity.lbl.gov/docs-usage. However, this is not present in the new user guide: https://www.sylabs.io/guides/3.0/user-guide/.

I realise that `singularity --help` exists, but it's very common and useful to have a command reference online as well.

**Comment by GodloveD** [comment]
That section has been intentionally omitted because it's a pita to create and keep up to date and it's basically duplicated from `--help`.  But if there is very good reason to go to this effort we can do so.  What's the reason?

**Comment by multimeric** [comment]
In my case, it made sharing links to documentation easier, as well as investigating how to use Singularity before I actually installed it. I think it's also the first place developers look when investigating a tool, since the CLI is how they will interact with it.

I notice that the CLI library you're using (Cobra) is able to generate ReST/markdown documentation (https://github.com/spf13/cobra#generating-documentation-for-your-command), and you're using Sphinx to generate the documentation, which supports ReST. Might this be a maintainable way to work this in?

If you're interested in such an integration, I'd be happy to look into implementing it. The only difficulty I can see is in cloning the appropriate version of Singularity for the associated docs, but you've probably already solved that problem, since the docs are versioned.

**Comment by GodloveD** [comment]
Thanks for your feedback @TMiguelT. You bring up some good points. If you've got a cobra-based method that we could use to auto-generate some command doc goodness, I'm all for it! Care to create a PR?

**Comment by multimeric** [comment]
Out of interest, do you have an automated build process, or are they generated manually for each release?

**Comment by multimeric** [comment]
Also, the singularity userdocs will need a copy of the singularity source code in order to do this. Do you have a preference how I should do this? Can the userdocs include singularity as a submodule? I could also add a target in the Makefile that clones singularity but that's a tad less elegant.

**Comment by multimeric** [comment]
Actually it looks like I'll have to PR Singularity itself to get it to build docs. Importing it from outside is a nightmare (https://stackoverflow.com/questions/54360585/importing-a-go-package-from-github-that-uses-native-c-code?noredirect=1#comment95537848_54360585)
