### ISSUE TITLE
need some MPI documentation

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity-userdocs#77]
This has been a glaring shortcoming for far too long.  We need a good guide explaining how to run MPI jobs using the hybrid model in Singularity.

**Comment by GodloveD** [comment]
Some useful links.

https://github.com/GodloveD/TAMUQ-workshop/tree/master/mpi
https://github.com/sylabs/examples/tree/master/machinelearning/horovod
http://mpitutorial.com/tutorials/mpi-hello-world/
https://singularity.lbl.gov/docs-hpc

I think it would be nice if the page had 2 sections.  The first section can talk about how to do MPI using the traditional "hybrid" approach.

Then if we can get this working and it seems useful and everything, maybe we can have a second section that uses the following approach (presented at the Singularity user group by @AdamSimpson).  

```
HOSTFILE=".hostfile.${SLURM_JOB_ID}"
for host in $(scontrol show hostnames); do
    echo "${host}" >>${HOSTFILE}
done

OMPI_MCA_plm=rsh
OMPI_MCA_plm_rsh_args='-o PubKeyAcceptedKeyTypes=+ssh-ds -o ...'
OMPI_MCA_orte_launch_agent="singularity run --nv nvidia.simg orted"

singularity run nvidia.simg mpirun --hostfile $HOSTFILE cmd
```

**Comment by dtrudg** [comment]
Hybrid MPI model example is now given at: https://sylabs.io/guides/3.4/user-guide/mpi.html
